# https://github.com/stackblitz-labs/pkg.pr.new
name: Preview Release

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to release preview'
        required: true
        default: 'main'

permissions:
  contents: read

jobs:
  preview:
    if: github.repository == 'rstackjs/storybook-rsbuild'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 1
          ref: ${{ github.event.inputs.ref }}

      - name: Install pnpm
        run: |
          npm install -g corepack@latest --force
          corepack enable

      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: changes
        with:
          filters: |
            changed:
              - "packages/**"
              - "pnpm-lock.yaml"

      - name: Setup Node.js
        if: steps.changes.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        if: steps.changes.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        run: pnpm install

      - name: Publish Preview
        if: steps.changes.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        run: pnpx pkg-pr-new publish --compact --pnpm ./packages/*
